"use client";
import { Inter, Outfit, Nunito } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { UserMemberContext } from "./_context/UserMemberContext";
import { useState } from "react";

const nunito = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Manish Ed-Tech",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isMember, setIsMember] = useState(false);
  return (
    <ClerkProvider>
      <UserMemberContext.Provider value={{ isMember, setIsMember }}>
        <html lang="en">
          <body className={nunito.className}>
            {children}
            <Toaster richColors />
          </body>
        </html>
      </UserMemberContext.Provider>
    </ClerkProvider>
  );
}
